### ISSUE TITLE
Certifacate used in package query expired

### ISSUE THREAD

**Issue by marcelovbcfilho** [atom-ide-community/atom#498] opened 2023-06-20 13:06 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Download the latest available release 1.63.0-dev-82d5fb463 at the moment.
2. Go to the packages section
3. Try to search by anything

**Expected behavior:**

I expect that all packages matching my query paramater were listed.

**Actual behavior:**

An error occur, when clicking on details it appears that the packages server certificate is expired.

**Reproduces how often:**

Always.

### Versions

1.63.0-dev-82d5fb463

### Additional Information

Here is an image where I try to search by multiple terms and the certificate error keeps appearing.

![Screenshot 2023-06-20 100152](https://github.com/atom-community/atom/assets/51462138/619eb0a4-7c3f-467f-9601-0dee80767374)

**Comment by icecream17** [comment] 2023-06-20 15:23
Yeah the atom packages website has been taken down and redirected to the sunset announcement. The easiest solution right now is probably to use pulsar's package API tbh

**Comment by icecream17** [comment] 2023-10-03 23:08
duplicate of #459

**Closed as completed by icecream17** 2023-10-03 23:08 UTC
Labels: Atom Packages
